### ISSUE TITLE
Usage tracker privacy disclaimer

### ISSUE THREAD

**Issue by aXu-AP** [BtheDestroyer/GodotVCamera#10]
**Is your feature request related to a problem? Please describe.**
I noticed that there's an usage tracker now and it works by sending current project name to remote server. I feel some might take this as a privacy infringement.

**Describe the solution you'd like**
Add a disclaimer to readme stating what data is being sent and for what purposes, if one enables the plugin. Also consider hashing the project name before sending it instead of sending plain text. Makes it more anonymous, takes off the risk that somebody uses project name as a password somewhere 😆

**Comment by Bryce-Dixon** [comment]
TL;DR: Sure, even though I might think the reasoning isn't perfect.

**************

> Add a disclaimer to readme stating what data is being sent and for what purposes

This is an understandable request, so sure. It's just being used for counting the number of projects it's being used in (the "Used in X projects" badge in the Readme).

> Also consider hashing the project name before sending it instead of sending plain text. Makes it more anonymous, takes off the risk that somebody uses project name as a password somewhere

This seems like a "security through obscurity" measure? Since I'm just using the name to determine if a project is unique, hashing it wouldn't harm that functionality, but the idea of a project's name needing to be secret (especially when I'm pretty sure it's included in exported projects) is kind of hard to believe.

**Comment by Bryce-Dixon** [comment]
I've updated the Readme and will hash the project name in a future commit.

**Comment by Bryce-Dixon** [comment]
IMO, it'd be better if Godot adds this functionality themselves. It'd be nice if they tracked the number of times an asset has been downloaded, since that's realistically all I'm trying to do, and it'd be way less scary than having a random little code snippet making some "phone home" request.

**Comment by Bryce-Dixon** [comment]
Hashed project name in commit fb57af9

**Comment by aXu-AP** [comment]
Yeah there's a lot of functionality missing from Godot Asset Library... I hope it'll improve over time.

> the idea of a project's name needing to be secret (especially when I'm pretty sure it's included in exported projects) is kind of hard to believe.

Well, people can rise a big noise even about anonymous telemetry, go figure 🤷‍♂️ Also not all projects are public.
